### ISSUE TITLE
Model load error

### ISSUE THREAD

**Issue by hatchetProject** [NVlabs/ASG#1]
Hi, 
I am currently using the code but cannot load the pretrained model correctly.
The ASG pretrained model (the one with 61% acc) has about 620 state_dict keys, while the model in code (I used the one defined in train.py) only has 526 state_dict keys, and the error message says that there are missing keys (such as layer1.0.bn1.num_batches_tracked).

I also found out that all of the missing keys has a common attribute: "num_batches_tracked". So I am wondering how is the pretrained ASG model defined exactly?

Thanks a lot if you can solve this issue for me. 

P.S. Is it OK that I ignore the missing keys by using model.load_state_dict(strict=False)?

**Comment by chenwydj** [comment]
Hi @hatchetProject!

Thank you for your interest in our work!

Yes, it is ok to ignore `num_batches_tracked`. Please see [here](https://discuss.pytorch.org/t/unexpected-key-in-state-dict-bn1-num-batches-tracked/29454).
